"""add table layout fields and reservation table_id

Revision ID: a4199c248f42
Revises: 0de9ccbfe93e
Create Date: 2026-08-13 11:49:53.332834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4199c248f42'
down_revision = '0de9ccbfe93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reservations_table_id', 'tables', ['table_id'], ['id'])

    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shape', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pos_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pos_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('width')
        batch_op.drop_column('color')
        batch_op.drop_column('pos_y')
        batch_op.drop_column('pos_x')
        batch_op.drop_column('shape')
        batch_op.drop_column('capacity')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservations_table_id', type_='foreignkey')
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###
